//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace StateMagic.Designer.ModelService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelSummary", Namespace="http://v1.model.services.statemagic.com/")]
    public partial class ModelSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ModelDataIDField;
        
        private string ModelNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ModelDataID {
            get {
                return this.ModelDataIDField;
            }
            set {
                if ((this.ModelDataIDField.Equals(value) != true)) {
                    this.ModelDataIDField = value;
                    this.RaisePropertyChanged("ModelDataID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateModel", Namespace="http://v1.model.services.statemagic.com/")]
    public partial class StateModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ModelIDField;
        
        private System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.State> StatesField;
        
        private System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.Transition> TransitionsField;
        
        private string ModelNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.State> States {
            get {
                return this.StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatesField, value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.Transition> Transitions {
            get {
                return this.TransitionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransitionsField, value) != true)) {
                    this.TransitionsField = value;
                    this.RaisePropertyChanged("Transitions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://v1.model.services.statemagic.com/")]
    public partial class State : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int StateIDField;
        
        private string NameField;
        
        private bool DefaultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transition", Namespace="http://v1.model.services.statemagic.com/")]
    public partial class Transition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int SourceStateRefField;
        
        private int DestinationStateRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SourceStateRef {
            get {
                return this.SourceStateRefField;
            }
            set {
                if ((this.SourceStateRefField.Equals(value) != true)) {
                    this.SourceStateRefField = value;
                    this.RaisePropertyChanged("SourceStateRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int DestinationStateRef {
            get {
                return this.DestinationStateRefField;
            }
            set {
                if ((this.DestinationStateRefField.Equals(value) != true)) {
                    this.DestinationStateRefField = value;
                    this.RaisePropertyChanged("DestinationStateRef");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://v1.model.services.statemagic.com/", ConfigurationName="ModelService.ModelServicesSoap")]
    public interface ModelServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://v1.model.services.statemagic.com/GetAllModels", ReplyAction="*")]
        System.IAsyncResult BeginGetAllModels(StateMagic.Designer.ModelService.GetAllModelsRequest request, System.AsyncCallback callback, object asyncState);
        
        StateMagic.Designer.ModelService.GetAllModelsResponse EndGetAllModels(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://v1.model.services.statemagic.com/GetModel", ReplyAction="*")]
        System.IAsyncResult BeginGetModel(StateMagic.Designer.ModelService.GetModelRequest request, System.AsyncCallback callback, object asyncState);
        
        StateMagic.Designer.ModelService.GetModelResponse EndGetModel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://v1.model.services.statemagic.com/SaveModel", ReplyAction="*")]
        System.IAsyncResult BeginSaveModel(StateMagic.Designer.ModelService.SaveModelRequest request, System.AsyncCallback callback, object asyncState);
        
        StateMagic.Designer.ModelService.SaveModelResponse EndSaveModel(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllModelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllModels", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelService.GetAllModelsRequestBody Body;
        
        public GetAllModelsRequest() {
        }
        
        public GetAllModelsRequest(StateMagic.Designer.ModelService.GetAllModelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class GetAllModelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid apiKey;
        
        public GetAllModelsRequestBody() {
        }
        
        public GetAllModelsRequestBody(string username, System.Guid apiKey) {
            this.username = username;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllModelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllModelsResponse", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelService.GetAllModelsResponseBody Body;
        
        public GetAllModelsResponse() {
        }
        
        public GetAllModelsResponse(StateMagic.Designer.ModelService.GetAllModelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class GetAllModelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.ModelSummary> GetAllModelsResult;
        
        public GetAllModelsResponseBody() {
        }
        
        public GetAllModelsResponseBody(System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.ModelSummary> GetAllModelsResult) {
            this.GetAllModelsResult = GetAllModelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModel", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelService.GetModelRequestBody Body;
        
        public GetModelRequest() {
        }
        
        public GetModelRequest(StateMagic.Designer.ModelService.GetModelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class GetModelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int modelId;
        
        public GetModelRequestBody() {
        }
        
        public GetModelRequestBody(string username, System.Guid apiKey, int modelId) {
            this.username = username;
            this.apiKey = apiKey;
            this.modelId = modelId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModelResponse", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelService.GetModelResponseBody Body;
        
        public GetModelResponse() {
        }
        
        public GetModelResponse(StateMagic.Designer.ModelService.GetModelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class GetModelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StateMagic.Designer.ModelService.StateModel GetModelResult;
        
        public GetModelResponseBody() {
        }
        
        public GetModelResponseBody(StateMagic.Designer.ModelService.StateModel GetModelResult) {
            this.GetModelResult = GetModelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveModel", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelService.SaveModelRequestBody Body;
        
        public SaveModelRequest() {
        }
        
        public SaveModelRequest(StateMagic.Designer.ModelService.SaveModelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class SaveModelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public StateMagic.Designer.ModelService.StateModel model;
        
        public SaveModelRequestBody() {
        }
        
        public SaveModelRequestBody(string username, System.Guid apiKey, string password, StateMagic.Designer.ModelService.StateModel model) {
            this.username = username;
            this.apiKey = apiKey;
            this.password = password;
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveModelResponse", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelService.SaveModelResponseBody Body;
        
        public SaveModelResponse() {
        }
        
        public SaveModelResponse(StateMagic.Designer.ModelService.SaveModelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveModelResponseBody {
        
        public SaveModelResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ModelServicesSoapChannel : StateMagic.Designer.ModelService.ModelServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllModelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllModelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.ModelSummary> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.ModelSummary>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetModelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetModelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public StateMagic.Designer.ModelService.StateModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((StateMagic.Designer.ModelService.StateModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelServicesSoapClient : System.ServiceModel.ClientBase<StateMagic.Designer.ModelService.ModelServicesSoap>, StateMagic.Designer.ModelService.ModelServicesSoap {
        
        private BeginOperationDelegate onBeginGetAllModelsDelegate;
        
        private EndOperationDelegate onEndGetAllModelsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllModelsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetModelDelegate;
        
        private EndOperationDelegate onEndGetModelDelegate;
        
        private System.Threading.SendOrPostCallback onGetModelCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveModelDelegate;
        
        private EndOperationDelegate onEndSaveModelDelegate;
        
        private System.Threading.SendOrPostCallback onSaveModelCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ModelServicesSoapClient() {
        }
        
        public ModelServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAllModelsCompletedEventArgs> GetAllModelsCompleted;
        
        public event System.EventHandler<GetModelCompletedEventArgs> GetModelCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveModelCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult StateMagic.Designer.ModelService.ModelServicesSoap.BeginGetAllModels(StateMagic.Designer.ModelService.GetAllModelsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllModels(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetAllModels(string username, System.Guid apiKey, System.AsyncCallback callback, object asyncState) {
            StateMagic.Designer.ModelService.GetAllModelsRequest inValue = new StateMagic.Designer.ModelService.GetAllModelsRequest();
            inValue.Body = new StateMagic.Designer.ModelService.GetAllModelsRequestBody();
            inValue.Body.username = username;
            inValue.Body.apiKey = apiKey;
            return ((StateMagic.Designer.ModelService.ModelServicesSoap)(this)).BeginGetAllModels(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StateMagic.Designer.ModelService.GetAllModelsResponse StateMagic.Designer.ModelService.ModelServicesSoap.EndGetAllModels(System.IAsyncResult result) {
            return base.Channel.EndGetAllModels(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.ModelSummary> EndGetAllModels(System.IAsyncResult result) {
            StateMagic.Designer.ModelService.GetAllModelsResponse retVal = ((StateMagic.Designer.ModelService.ModelServicesSoap)(this)).EndGetAllModels(result);
            return retVal.Body.GetAllModelsResult;
        }
        
        private System.IAsyncResult OnBeginGetAllModels(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            System.Guid apiKey = ((System.Guid)(inValues[1]));
            return this.BeginGetAllModels(username, apiKey, callback, asyncState);
        }
        
        private object[] OnEndGetAllModels(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<StateMagic.Designer.ModelService.ModelSummary> retVal = this.EndGetAllModels(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllModelsCompleted(object state) {
            if ((this.GetAllModelsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllModelsCompleted(this, new GetAllModelsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllModelsAsync(string username, System.Guid apiKey) {
            this.GetAllModelsAsync(username, apiKey, null);
        }
        
        public void GetAllModelsAsync(string username, System.Guid apiKey, object userState) {
            if ((this.onBeginGetAllModelsDelegate == null)) {
                this.onBeginGetAllModelsDelegate = new BeginOperationDelegate(this.OnBeginGetAllModels);
            }
            if ((this.onEndGetAllModelsDelegate == null)) {
                this.onEndGetAllModelsDelegate = new EndOperationDelegate(this.OnEndGetAllModels);
            }
            if ((this.onGetAllModelsCompletedDelegate == null)) {
                this.onGetAllModelsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllModelsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllModelsDelegate, new object[] {
                        username,
                        apiKey}, this.onEndGetAllModelsDelegate, this.onGetAllModelsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult StateMagic.Designer.ModelService.ModelServicesSoap.BeginGetModel(StateMagic.Designer.ModelService.GetModelRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetModel(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetModel(string username, System.Guid apiKey, int modelId, System.AsyncCallback callback, object asyncState) {
            StateMagic.Designer.ModelService.GetModelRequest inValue = new StateMagic.Designer.ModelService.GetModelRequest();
            inValue.Body = new StateMagic.Designer.ModelService.GetModelRequestBody();
            inValue.Body.username = username;
            inValue.Body.apiKey = apiKey;
            inValue.Body.modelId = modelId;
            return ((StateMagic.Designer.ModelService.ModelServicesSoap)(this)).BeginGetModel(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StateMagic.Designer.ModelService.GetModelResponse StateMagic.Designer.ModelService.ModelServicesSoap.EndGetModel(System.IAsyncResult result) {
            return base.Channel.EndGetModel(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private StateMagic.Designer.ModelService.StateModel EndGetModel(System.IAsyncResult result) {
            StateMagic.Designer.ModelService.GetModelResponse retVal = ((StateMagic.Designer.ModelService.ModelServicesSoap)(this)).EndGetModel(result);
            return retVal.Body.GetModelResult;
        }
        
        private System.IAsyncResult OnBeginGetModel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            System.Guid apiKey = ((System.Guid)(inValues[1]));
            int modelId = ((int)(inValues[2]));
            return this.BeginGetModel(username, apiKey, modelId, callback, asyncState);
        }
        
        private object[] OnEndGetModel(System.IAsyncResult result) {
            StateMagic.Designer.ModelService.StateModel retVal = this.EndGetModel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetModelCompleted(object state) {
            if ((this.GetModelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetModelCompleted(this, new GetModelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetModelAsync(string username, System.Guid apiKey, int modelId) {
            this.GetModelAsync(username, apiKey, modelId, null);
        }
        
        public void GetModelAsync(string username, System.Guid apiKey, int modelId, object userState) {
            if ((this.onBeginGetModelDelegate == null)) {
                this.onBeginGetModelDelegate = new BeginOperationDelegate(this.OnBeginGetModel);
            }
            if ((this.onEndGetModelDelegate == null)) {
                this.onEndGetModelDelegate = new EndOperationDelegate(this.OnEndGetModel);
            }
            if ((this.onGetModelCompletedDelegate == null)) {
                this.onGetModelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetModelCompleted);
            }
            base.InvokeAsync(this.onBeginGetModelDelegate, new object[] {
                        username,
                        apiKey,
                        modelId}, this.onEndGetModelDelegate, this.onGetModelCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult StateMagic.Designer.ModelService.ModelServicesSoap.BeginSaveModel(StateMagic.Designer.ModelService.SaveModelRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveModel(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSaveModel(string username, System.Guid apiKey, string password, StateMagic.Designer.ModelService.StateModel model, System.AsyncCallback callback, object asyncState) {
            StateMagic.Designer.ModelService.SaveModelRequest inValue = new StateMagic.Designer.ModelService.SaveModelRequest();
            inValue.Body = new StateMagic.Designer.ModelService.SaveModelRequestBody();
            inValue.Body.username = username;
            inValue.Body.apiKey = apiKey;
            inValue.Body.password = password;
            inValue.Body.model = model;
            return ((StateMagic.Designer.ModelService.ModelServicesSoap)(this)).BeginSaveModel(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StateMagic.Designer.ModelService.SaveModelResponse StateMagic.Designer.ModelService.ModelServicesSoap.EndSaveModel(System.IAsyncResult result) {
            return base.Channel.EndSaveModel(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndSaveModel(System.IAsyncResult result) {
            StateMagic.Designer.ModelService.SaveModelResponse retVal = ((StateMagic.Designer.ModelService.ModelServicesSoap)(this)).EndSaveModel(result);
        }
        
        private System.IAsyncResult OnBeginSaveModel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            System.Guid apiKey = ((System.Guid)(inValues[1]));
            string password = ((string)(inValues[2]));
            StateMagic.Designer.ModelService.StateModel model = ((StateMagic.Designer.ModelService.StateModel)(inValues[3]));
            return this.BeginSaveModel(username, apiKey, password, model, callback, asyncState);
        }
        
        private object[] OnEndSaveModel(System.IAsyncResult result) {
            this.EndSaveModel(result);
            return null;
        }
        
        private void OnSaveModelCompleted(object state) {
            if ((this.SaveModelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveModelCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveModelAsync(string username, System.Guid apiKey, string password, StateMagic.Designer.ModelService.StateModel model) {
            this.SaveModelAsync(username, apiKey, password, model, null);
        }
        
        public void SaveModelAsync(string username, System.Guid apiKey, string password, StateMagic.Designer.ModelService.StateModel model, object userState) {
            if ((this.onBeginSaveModelDelegate == null)) {
                this.onBeginSaveModelDelegate = new BeginOperationDelegate(this.OnBeginSaveModel);
            }
            if ((this.onEndSaveModelDelegate == null)) {
                this.onEndSaveModelDelegate = new EndOperationDelegate(this.OnEndSaveModel);
            }
            if ((this.onSaveModelCompletedDelegate == null)) {
                this.onSaveModelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveModelCompleted);
            }
            base.InvokeAsync(this.onBeginSaveModelDelegate, new object[] {
                        username,
                        apiKey,
                        password,
                        model}, this.onEndSaveModelDelegate, this.onSaveModelCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override StateMagic.Designer.ModelService.ModelServicesSoap CreateChannel() {
            return new ModelServicesSoapClientChannel(this);
        }
        
        private class ModelServicesSoapClientChannel : ChannelBase<StateMagic.Designer.ModelService.ModelServicesSoap>, StateMagic.Designer.ModelService.ModelServicesSoap {
            
            public ModelServicesSoapClientChannel(System.ServiceModel.ClientBase<StateMagic.Designer.ModelService.ModelServicesSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllModels(StateMagic.Designer.ModelService.GetAllModelsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetAllModels", _args, callback, asyncState);
                return _result;
            }
            
            public StateMagic.Designer.ModelService.GetAllModelsResponse EndGetAllModels(System.IAsyncResult result) {
                object[] _args = new object[0];
                StateMagic.Designer.ModelService.GetAllModelsResponse _result = ((StateMagic.Designer.ModelService.GetAllModelsResponse)(base.EndInvoke("GetAllModels", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetModel(StateMagic.Designer.ModelService.GetModelRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetModel", _args, callback, asyncState);
                return _result;
            }
            
            public StateMagic.Designer.ModelService.GetModelResponse EndGetModel(System.IAsyncResult result) {
                object[] _args = new object[0];
                StateMagic.Designer.ModelService.GetModelResponse _result = ((StateMagic.Designer.ModelService.GetModelResponse)(base.EndInvoke("GetModel", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveModel(StateMagic.Designer.ModelService.SaveModelRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SaveModel", _args, callback, asyncState);
                return _result;
            }
            
            public StateMagic.Designer.ModelService.SaveModelResponse EndSaveModel(System.IAsyncResult result) {
                object[] _args = new object[0];
                StateMagic.Designer.ModelService.SaveModelResponse _result = ((StateMagic.Designer.ModelService.SaveModelResponse)(base.EndInvoke("SaveModel", _args, result)));
                return _result;
            }
        }
    }
}
