//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace StateMagic.Designer.ModelServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelSummary", Namespace="http://v1.model.services.statemagic.com/")]
    public partial class ModelSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ModelDataIDField;
        
        private string ModelNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ModelDataID {
            get {
                return this.ModelDataIDField;
            }
            set {
                if ((this.ModelDataIDField.Equals(value) != true)) {
                    this.ModelDataIDField = value;
                    this.RaisePropertyChanged("ModelDataID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateModel", Namespace="http://v1.model.services.statemagic.com/")]
    public partial class StateModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ModelIDField;
        
        private System.Collections.Generic.List<StateMagic.Designer.ModelServices.State> StatesField;
        
        private System.Collections.Generic.List<StateMagic.Designer.ModelServices.Transition> TransitionsField;
        
        private string ModelNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<StateMagic.Designer.ModelServices.State> States {
            get {
                return this.StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatesField, value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<StateMagic.Designer.ModelServices.Transition> Transitions {
            get {
                return this.TransitionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransitionsField, value) != true)) {
                    this.TransitionsField = value;
                    this.RaisePropertyChanged("Transitions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://v1.model.services.statemagic.com/")]
    public partial class State : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int StateIDField;
        
        private string NameField;
        
        private bool DefaultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transition", Namespace="http://v1.model.services.statemagic.com/")]
    public partial class Transition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int SourceStateRefField;
        
        private int DestinationStateRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SourceStateRef {
            get {
                return this.SourceStateRefField;
            }
            set {
                if ((this.SourceStateRefField.Equals(value) != true)) {
                    this.SourceStateRefField = value;
                    this.RaisePropertyChanged("SourceStateRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int DestinationStateRef {
            get {
                return this.DestinationStateRefField;
            }
            set {
                if ((this.DestinationStateRefField.Equals(value) != true)) {
                    this.DestinationStateRefField = value;
                    this.RaisePropertyChanged("DestinationStateRef");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://v1.model.services.statemagic.com/", ConfigurationName="ModelServices.ModelServicesSoap")]
    public interface ModelServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://v1.model.services.statemagic.com/GetAllModels", ReplyAction="*")]
        System.IAsyncResult BeginGetAllModels(StateMagic.Designer.ModelServices.GetAllModelsRequest request, System.AsyncCallback callback, object asyncState);
        
        StateMagic.Designer.ModelServices.GetAllModelsResponse EndGetAllModels(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://v1.model.services.statemagic.com/GetModel", ReplyAction="*")]
        System.IAsyncResult BeginGetModel(StateMagic.Designer.ModelServices.GetModelRequest request, System.AsyncCallback callback, object asyncState);
        
        StateMagic.Designer.ModelServices.GetModelResponse EndGetModel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://v1.model.services.statemagic.com/SaveModel", ReplyAction="*")]
        System.IAsyncResult BeginSaveModel(StateMagic.Designer.ModelServices.SaveModelRequest request, System.AsyncCallback callback, object asyncState);
        
        StateMagic.Designer.ModelServices.SaveModelResponse EndSaveModel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://v1.model.services.statemagic.com/CreateAccount", ReplyAction="*")]
        System.IAsyncResult BeginCreateAccount(StateMagic.Designer.ModelServices.CreateAccountRequest request, System.AsyncCallback callback, object asyncState);
        
        StateMagic.Designer.ModelServices.CreateAccountResponse EndCreateAccount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://v1.model.services.statemagic.com/LogIn", ReplyAction="*")]
        System.IAsyncResult BeginLogIn(StateMagic.Designer.ModelServices.LogInRequest request, System.AsyncCallback callback, object asyncState);
        
        StateMagic.Designer.ModelServices.LogInResponse EndLogIn(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllModelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllModels", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.GetAllModelsRequestBody Body;
        
        public GetAllModelsRequest() {
        }
        
        public GetAllModelsRequest(StateMagic.Designer.ModelServices.GetAllModelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class GetAllModelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid systemKey;
        
        public GetAllModelsRequestBody() {
        }
        
        public GetAllModelsRequestBody(string username, System.Guid apiKey, System.Guid systemKey) {
            this.username = username;
            this.apiKey = apiKey;
            this.systemKey = systemKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllModelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllModelsResponse", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.GetAllModelsResponseBody Body;
        
        public GetAllModelsResponse() {
        }
        
        public GetAllModelsResponse(StateMagic.Designer.ModelServices.GetAllModelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class GetAllModelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<StateMagic.Designer.ModelServices.ModelSummary> GetAllModelsResult;
        
        public GetAllModelsResponseBody() {
        }
        
        public GetAllModelsResponseBody(System.Collections.Generic.List<StateMagic.Designer.ModelServices.ModelSummary> GetAllModelsResult) {
            this.GetAllModelsResult = GetAllModelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModel", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.GetModelRequestBody Body;
        
        public GetModelRequest() {
        }
        
        public GetModelRequest(StateMagic.Designer.ModelServices.GetModelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class GetModelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int modelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Guid systemKey;
        
        public GetModelRequestBody() {
        }
        
        public GetModelRequestBody(string username, System.Guid apiKey, int modelId, System.Guid systemKey) {
            this.username = username;
            this.apiKey = apiKey;
            this.modelId = modelId;
            this.systemKey = systemKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModelResponse", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.GetModelResponseBody Body;
        
        public GetModelResponse() {
        }
        
        public GetModelResponse(StateMagic.Designer.ModelServices.GetModelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class GetModelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StateMagic.Designer.ModelServices.StateModel GetModelResult;
        
        public GetModelResponseBody() {
        }
        
        public GetModelResponseBody(StateMagic.Designer.ModelServices.StateModel GetModelResult) {
            this.GetModelResult = GetModelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveModel", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.SaveModelRequestBody Body;
        
        public SaveModelRequest() {
        }
        
        public SaveModelRequest(StateMagic.Designer.ModelServices.SaveModelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class SaveModelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public StateMagic.Designer.ModelServices.StateModel model;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Guid systemKey;
        
        public SaveModelRequestBody() {
        }
        
        public SaveModelRequestBody(string username, System.Guid apiKey, StateMagic.Designer.ModelServices.StateModel model, System.Guid systemKey) {
            this.username = username;
            this.apiKey = apiKey;
            this.model = model;
            this.systemKey = systemKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveModelResponse", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.SaveModelResponseBody Body;
        
        public SaveModelResponse() {
        }
        
        public SaveModelResponse(StateMagic.Designer.ModelServices.SaveModelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class SaveModelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveModelResult;
        
        public SaveModelResponseBody() {
        }
        
        public SaveModelResponseBody(int SaveModelResult) {
            this.SaveModelResult = SaveModelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccount", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.CreateAccountRequestBody Body;
        
        public CreateAccountRequest() {
        }
        
        public CreateAccountRequest(StateMagic.Designer.ModelServices.CreateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class CreateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Guid systemKey;
        
        public CreateAccountRequestBody() {
        }
        
        public CreateAccountRequestBody(string username, System.Guid apiKey, string password, System.Guid systemKey) {
            this.username = username;
            this.apiKey = apiKey;
            this.password = password;
            this.systemKey = systemKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccountResponse", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.CreateAccountResponseBody Body;
        
        public CreateAccountResponse() {
        }
        
        public CreateAccountResponse(StateMagic.Designer.ModelServices.CreateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class CreateAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateAccountResult;
        
        public CreateAccountResponseBody() {
        }
        
        public CreateAccountResponseBody(bool CreateAccountResult) {
            this.CreateAccountResult = CreateAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(StateMagic.Designer.ModelServices.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Guid systemKey;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string username, string password, System.Guid apiKey, System.Guid systemKey) {
            this.username = username;
            this.password = password;
            this.apiKey = apiKey;
            this.systemKey = systemKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://v1.model.services.statemagic.com/", Order=0)]
        public StateMagic.Designer.ModelServices.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(StateMagic.Designer.ModelServices.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://v1.model.services.statemagic.com/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(System.Guid LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ModelServicesSoapChannel : StateMagic.Designer.ModelServices.ModelServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllModelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllModelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<StateMagic.Designer.ModelServices.ModelSummary> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<StateMagic.Designer.ModelServices.ModelSummary>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetModelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetModelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public StateMagic.Designer.ModelServices.StateModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((StateMagic.Designer.ModelServices.StateModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveModelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveModelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LogInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Guid Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelServicesSoapClient : System.ServiceModel.ClientBase<StateMagic.Designer.ModelServices.ModelServicesSoap>, StateMagic.Designer.ModelServices.ModelServicesSoap {
        
        private BeginOperationDelegate onBeginGetAllModelsDelegate;
        
        private EndOperationDelegate onEndGetAllModelsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllModelsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetModelDelegate;
        
        private EndOperationDelegate onEndGetModelDelegate;
        
        private System.Threading.SendOrPostCallback onGetModelCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveModelDelegate;
        
        private EndOperationDelegate onEndSaveModelDelegate;
        
        private System.Threading.SendOrPostCallback onSaveModelCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateAccountDelegate;
        
        private EndOperationDelegate onEndCreateAccountDelegate;
        
        private System.Threading.SendOrPostCallback onCreateAccountCompletedDelegate;
        
        private BeginOperationDelegate onBeginLogInDelegate;
        
        private EndOperationDelegate onEndLogInDelegate;
        
        private System.Threading.SendOrPostCallback onLogInCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ModelServicesSoapClient() {
        }
        
        public ModelServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAllModelsCompletedEventArgs> GetAllModelsCompleted;
        
        public event System.EventHandler<GetModelCompletedEventArgs> GetModelCompleted;
        
        public event System.EventHandler<SaveModelCompletedEventArgs> SaveModelCompleted;
        
        public event System.EventHandler<CreateAccountCompletedEventArgs> CreateAccountCompleted;
        
        public event System.EventHandler<LogInCompletedEventArgs> LogInCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult StateMagic.Designer.ModelServices.ModelServicesSoap.BeginGetAllModels(StateMagic.Designer.ModelServices.GetAllModelsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllModels(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetAllModels(string username, System.Guid apiKey, System.Guid systemKey, System.AsyncCallback callback, object asyncState) {
            StateMagic.Designer.ModelServices.GetAllModelsRequest inValue = new StateMagic.Designer.ModelServices.GetAllModelsRequest();
            inValue.Body = new StateMagic.Designer.ModelServices.GetAllModelsRequestBody();
            inValue.Body.username = username;
            inValue.Body.apiKey = apiKey;
            inValue.Body.systemKey = systemKey;
            return ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).BeginGetAllModels(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StateMagic.Designer.ModelServices.GetAllModelsResponse StateMagic.Designer.ModelServices.ModelServicesSoap.EndGetAllModels(System.IAsyncResult result) {
            return base.Channel.EndGetAllModels(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.Generic.List<StateMagic.Designer.ModelServices.ModelSummary> EndGetAllModels(System.IAsyncResult result) {
            StateMagic.Designer.ModelServices.GetAllModelsResponse retVal = ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).EndGetAllModels(result);
            return retVal.Body.GetAllModelsResult;
        }
        
        private System.IAsyncResult OnBeginGetAllModels(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            System.Guid apiKey = ((System.Guid)(inValues[1]));
            System.Guid systemKey = ((System.Guid)(inValues[2]));
            return this.BeginGetAllModels(username, apiKey, systemKey, callback, asyncState);
        }
        
        private object[] OnEndGetAllModels(System.IAsyncResult result) {
            System.Collections.Generic.List<StateMagic.Designer.ModelServices.ModelSummary> retVal = this.EndGetAllModels(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllModelsCompleted(object state) {
            if ((this.GetAllModelsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllModelsCompleted(this, new GetAllModelsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllModelsAsync(string username, System.Guid apiKey, System.Guid systemKey) {
            this.GetAllModelsAsync(username, apiKey, systemKey, null);
        }
        
        public void GetAllModelsAsync(string username, System.Guid apiKey, System.Guid systemKey, object userState) {
            if ((this.onBeginGetAllModelsDelegate == null)) {
                this.onBeginGetAllModelsDelegate = new BeginOperationDelegate(this.OnBeginGetAllModels);
            }
            if ((this.onEndGetAllModelsDelegate == null)) {
                this.onEndGetAllModelsDelegate = new EndOperationDelegate(this.OnEndGetAllModels);
            }
            if ((this.onGetAllModelsCompletedDelegate == null)) {
                this.onGetAllModelsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllModelsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllModelsDelegate, new object[] {
                        username,
                        apiKey,
                        systemKey}, this.onEndGetAllModelsDelegate, this.onGetAllModelsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult StateMagic.Designer.ModelServices.ModelServicesSoap.BeginGetModel(StateMagic.Designer.ModelServices.GetModelRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetModel(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetModel(string username, System.Guid apiKey, int modelId, System.Guid systemKey, System.AsyncCallback callback, object asyncState) {
            StateMagic.Designer.ModelServices.GetModelRequest inValue = new StateMagic.Designer.ModelServices.GetModelRequest();
            inValue.Body = new StateMagic.Designer.ModelServices.GetModelRequestBody();
            inValue.Body.username = username;
            inValue.Body.apiKey = apiKey;
            inValue.Body.modelId = modelId;
            inValue.Body.systemKey = systemKey;
            return ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).BeginGetModel(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StateMagic.Designer.ModelServices.GetModelResponse StateMagic.Designer.ModelServices.ModelServicesSoap.EndGetModel(System.IAsyncResult result) {
            return base.Channel.EndGetModel(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private StateMagic.Designer.ModelServices.StateModel EndGetModel(System.IAsyncResult result) {
            StateMagic.Designer.ModelServices.GetModelResponse retVal = ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).EndGetModel(result);
            return retVal.Body.GetModelResult;
        }
        
        private System.IAsyncResult OnBeginGetModel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            System.Guid apiKey = ((System.Guid)(inValues[1]));
            int modelId = ((int)(inValues[2]));
            System.Guid systemKey = ((System.Guid)(inValues[3]));
            return this.BeginGetModel(username, apiKey, modelId, systemKey, callback, asyncState);
        }
        
        private object[] OnEndGetModel(System.IAsyncResult result) {
            StateMagic.Designer.ModelServices.StateModel retVal = this.EndGetModel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetModelCompleted(object state) {
            if ((this.GetModelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetModelCompleted(this, new GetModelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetModelAsync(string username, System.Guid apiKey, int modelId, System.Guid systemKey) {
            this.GetModelAsync(username, apiKey, modelId, systemKey, null);
        }
        
        public void GetModelAsync(string username, System.Guid apiKey, int modelId, System.Guid systemKey, object userState) {
            if ((this.onBeginGetModelDelegate == null)) {
                this.onBeginGetModelDelegate = new BeginOperationDelegate(this.OnBeginGetModel);
            }
            if ((this.onEndGetModelDelegate == null)) {
                this.onEndGetModelDelegate = new EndOperationDelegate(this.OnEndGetModel);
            }
            if ((this.onGetModelCompletedDelegate == null)) {
                this.onGetModelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetModelCompleted);
            }
            base.InvokeAsync(this.onBeginGetModelDelegate, new object[] {
                        username,
                        apiKey,
                        modelId,
                        systemKey}, this.onEndGetModelDelegate, this.onGetModelCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult StateMagic.Designer.ModelServices.ModelServicesSoap.BeginSaveModel(StateMagic.Designer.ModelServices.SaveModelRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveModel(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSaveModel(string username, System.Guid apiKey, StateMagic.Designer.ModelServices.StateModel model, System.Guid systemKey, System.AsyncCallback callback, object asyncState) {
            StateMagic.Designer.ModelServices.SaveModelRequest inValue = new StateMagic.Designer.ModelServices.SaveModelRequest();
            inValue.Body = new StateMagic.Designer.ModelServices.SaveModelRequestBody();
            inValue.Body.username = username;
            inValue.Body.apiKey = apiKey;
            inValue.Body.model = model;
            inValue.Body.systemKey = systemKey;
            return ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).BeginSaveModel(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StateMagic.Designer.ModelServices.SaveModelResponse StateMagic.Designer.ModelServices.ModelServicesSoap.EndSaveModel(System.IAsyncResult result) {
            return base.Channel.EndSaveModel(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private int EndSaveModel(System.IAsyncResult result) {
            StateMagic.Designer.ModelServices.SaveModelResponse retVal = ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).EndSaveModel(result);
            return retVal.Body.SaveModelResult;
        }
        
        private System.IAsyncResult OnBeginSaveModel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            System.Guid apiKey = ((System.Guid)(inValues[1]));
            StateMagic.Designer.ModelServices.StateModel model = ((StateMagic.Designer.ModelServices.StateModel)(inValues[2]));
            System.Guid systemKey = ((System.Guid)(inValues[3]));
            return this.BeginSaveModel(username, apiKey, model, systemKey, callback, asyncState);
        }
        
        private object[] OnEndSaveModel(System.IAsyncResult result) {
            int retVal = this.EndSaveModel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveModelCompleted(object state) {
            if ((this.SaveModelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveModelCompleted(this, new SaveModelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveModelAsync(string username, System.Guid apiKey, StateMagic.Designer.ModelServices.StateModel model, System.Guid systemKey) {
            this.SaveModelAsync(username, apiKey, model, systemKey, null);
        }
        
        public void SaveModelAsync(string username, System.Guid apiKey, StateMagic.Designer.ModelServices.StateModel model, System.Guid systemKey, object userState) {
            if ((this.onBeginSaveModelDelegate == null)) {
                this.onBeginSaveModelDelegate = new BeginOperationDelegate(this.OnBeginSaveModel);
            }
            if ((this.onEndSaveModelDelegate == null)) {
                this.onEndSaveModelDelegate = new EndOperationDelegate(this.OnEndSaveModel);
            }
            if ((this.onSaveModelCompletedDelegate == null)) {
                this.onSaveModelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveModelCompleted);
            }
            base.InvokeAsync(this.onBeginSaveModelDelegate, new object[] {
                        username,
                        apiKey,
                        model,
                        systemKey}, this.onEndSaveModelDelegate, this.onSaveModelCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult StateMagic.Designer.ModelServices.ModelServicesSoap.BeginCreateAccount(StateMagic.Designer.ModelServices.CreateAccountRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateAccount(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCreateAccount(string username, System.Guid apiKey, string password, System.Guid systemKey, System.AsyncCallback callback, object asyncState) {
            StateMagic.Designer.ModelServices.CreateAccountRequest inValue = new StateMagic.Designer.ModelServices.CreateAccountRequest();
            inValue.Body = new StateMagic.Designer.ModelServices.CreateAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.apiKey = apiKey;
            inValue.Body.password = password;
            inValue.Body.systemKey = systemKey;
            return ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).BeginCreateAccount(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StateMagic.Designer.ModelServices.CreateAccountResponse StateMagic.Designer.ModelServices.ModelServicesSoap.EndCreateAccount(System.IAsyncResult result) {
            return base.Channel.EndCreateAccount(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndCreateAccount(System.IAsyncResult result) {
            StateMagic.Designer.ModelServices.CreateAccountResponse retVal = ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).EndCreateAccount(result);
            return retVal.Body.CreateAccountResult;
        }
        
        private System.IAsyncResult OnBeginCreateAccount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            System.Guid apiKey = ((System.Guid)(inValues[1]));
            string password = ((string)(inValues[2]));
            System.Guid systemKey = ((System.Guid)(inValues[3]));
            return this.BeginCreateAccount(username, apiKey, password, systemKey, callback, asyncState);
        }
        
        private object[] OnEndCreateAccount(System.IAsyncResult result) {
            bool retVal = this.EndCreateAccount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateAccountCompleted(object state) {
            if ((this.CreateAccountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateAccountCompleted(this, new CreateAccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateAccountAsync(string username, System.Guid apiKey, string password, System.Guid systemKey) {
            this.CreateAccountAsync(username, apiKey, password, systemKey, null);
        }
        
        public void CreateAccountAsync(string username, System.Guid apiKey, string password, System.Guid systemKey, object userState) {
            if ((this.onBeginCreateAccountDelegate == null)) {
                this.onBeginCreateAccountDelegate = new BeginOperationDelegate(this.OnBeginCreateAccount);
            }
            if ((this.onEndCreateAccountDelegate == null)) {
                this.onEndCreateAccountDelegate = new EndOperationDelegate(this.OnEndCreateAccount);
            }
            if ((this.onCreateAccountCompletedDelegate == null)) {
                this.onCreateAccountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateAccountCompleted);
            }
            base.InvokeAsync(this.onBeginCreateAccountDelegate, new object[] {
                        username,
                        apiKey,
                        password,
                        systemKey}, this.onEndCreateAccountDelegate, this.onCreateAccountCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult StateMagic.Designer.ModelServices.ModelServicesSoap.BeginLogIn(StateMagic.Designer.ModelServices.LogInRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogIn(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginLogIn(string username, string password, System.Guid apiKey, System.Guid systemKey, System.AsyncCallback callback, object asyncState) {
            StateMagic.Designer.ModelServices.LogInRequest inValue = new StateMagic.Designer.ModelServices.LogInRequest();
            inValue.Body = new StateMagic.Designer.ModelServices.LogInRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.apiKey = apiKey;
            inValue.Body.systemKey = systemKey;
            return ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).BeginLogIn(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StateMagic.Designer.ModelServices.LogInResponse StateMagic.Designer.ModelServices.ModelServicesSoap.EndLogIn(System.IAsyncResult result) {
            return base.Channel.EndLogIn(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Guid EndLogIn(System.IAsyncResult result) {
            StateMagic.Designer.ModelServices.LogInResponse retVal = ((StateMagic.Designer.ModelServices.ModelServicesSoap)(this)).EndLogIn(result);
            return retVal.Body.LogInResult;
        }
        
        private System.IAsyncResult OnBeginLogIn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            System.Guid apiKey = ((System.Guid)(inValues[2]));
            System.Guid systemKey = ((System.Guid)(inValues[3]));
            return this.BeginLogIn(username, password, apiKey, systemKey, callback, asyncState);
        }
        
        private object[] OnEndLogIn(System.IAsyncResult result) {
            System.Guid retVal = this.EndLogIn(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLogInCompleted(object state) {
            if ((this.LogInCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogInCompleted(this, new LogInCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogInAsync(string username, string password, System.Guid apiKey, System.Guid systemKey) {
            this.LogInAsync(username, password, apiKey, systemKey, null);
        }
        
        public void LogInAsync(string username, string password, System.Guid apiKey, System.Guid systemKey, object userState) {
            if ((this.onBeginLogInDelegate == null)) {
                this.onBeginLogInDelegate = new BeginOperationDelegate(this.OnBeginLogIn);
            }
            if ((this.onEndLogInDelegate == null)) {
                this.onEndLogInDelegate = new EndOperationDelegate(this.OnEndLogIn);
            }
            if ((this.onLogInCompletedDelegate == null)) {
                this.onLogInCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogInCompleted);
            }
            base.InvokeAsync(this.onBeginLogInDelegate, new object[] {
                        username,
                        password,
                        apiKey,
                        systemKey}, this.onEndLogInDelegate, this.onLogInCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override StateMagic.Designer.ModelServices.ModelServicesSoap CreateChannel() {
            return new ModelServicesSoapClientChannel(this);
        }
        
        private class ModelServicesSoapClientChannel : ChannelBase<StateMagic.Designer.ModelServices.ModelServicesSoap>, StateMagic.Designer.ModelServices.ModelServicesSoap {
            
            public ModelServicesSoapClientChannel(System.ServiceModel.ClientBase<StateMagic.Designer.ModelServices.ModelServicesSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllModels(StateMagic.Designer.ModelServices.GetAllModelsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetAllModels", _args, callback, asyncState);
                return _result;
            }
            
            public StateMagic.Designer.ModelServices.GetAllModelsResponse EndGetAllModels(System.IAsyncResult result) {
                object[] _args = new object[0];
                StateMagic.Designer.ModelServices.GetAllModelsResponse _result = ((StateMagic.Designer.ModelServices.GetAllModelsResponse)(base.EndInvoke("GetAllModels", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetModel(StateMagic.Designer.ModelServices.GetModelRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetModel", _args, callback, asyncState);
                return _result;
            }
            
            public StateMagic.Designer.ModelServices.GetModelResponse EndGetModel(System.IAsyncResult result) {
                object[] _args = new object[0];
                StateMagic.Designer.ModelServices.GetModelResponse _result = ((StateMagic.Designer.ModelServices.GetModelResponse)(base.EndInvoke("GetModel", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveModel(StateMagic.Designer.ModelServices.SaveModelRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SaveModel", _args, callback, asyncState);
                return _result;
            }
            
            public StateMagic.Designer.ModelServices.SaveModelResponse EndSaveModel(System.IAsyncResult result) {
                object[] _args = new object[0];
                StateMagic.Designer.ModelServices.SaveModelResponse _result = ((StateMagic.Designer.ModelServices.SaveModelResponse)(base.EndInvoke("SaveModel", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateAccount(StateMagic.Designer.ModelServices.CreateAccountRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CreateAccount", _args, callback, asyncState);
                return _result;
            }
            
            public StateMagic.Designer.ModelServices.CreateAccountResponse EndCreateAccount(System.IAsyncResult result) {
                object[] _args = new object[0];
                StateMagic.Designer.ModelServices.CreateAccountResponse _result = ((StateMagic.Designer.ModelServices.CreateAccountResponse)(base.EndInvoke("CreateAccount", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogIn(StateMagic.Designer.ModelServices.LogInRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("LogIn", _args, callback, asyncState);
                return _result;
            }
            
            public StateMagic.Designer.ModelServices.LogInResponse EndLogIn(System.IAsyncResult result) {
                object[] _args = new object[0];
                StateMagic.Designer.ModelServices.LogInResponse _result = ((StateMagic.Designer.ModelServices.LogInResponse)(base.EndInvoke("LogIn", _args, result)));
                return _result;
            }
        }
    }
}
